# -*- coding: utf-8 -*-
"""CardFraudDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBiUZT9PDAKzh8-U63TIIhW1mcvDfwa2
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('/content/creditcard.csv')
df.tail()

fraud = df.loc[df['Class'] == 1]
real = df.loc[df['Class'] == 0]

len(real)

len(fraud)

colours = ['red']
sns.relplot(x= 'Amount', y= 'Time',hue= 'Class', data=df)

from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

X = df.iloc[:,:-1]
Y = df['Class']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.35)

model = linear_model.LogisticRegression()

model.fit(x_train, y_train)

y_pred = np.array(model.predict(x_test))

y = np.array(y_test)

print(confusion_matrix(y_test, y_pred))

print('Accuracy: ', model.score(x_test, y_test)* 100)

print(classification_report(y_test, y_pred))

